export const MOONRAKER_RUNTIME_OBJECTS = [
  'webhooks',
  'toolhead',
  'gcode_move',
  'print_stats',
  'virtual_sdcard',
  'extruder',
  'heater_bed',
  'fan',
  'display_status',
  'pause_resume',
  'idle_timeout',
  'gcode_macro _TREED_PROFILE',
  'gcode_macro _TREED_GEOMETRY_CFG',
  'gcode_macro _TREED_PAUSE_STATE',
  'gcode_macro _TREED_CAM_STATE',
  'gcode_macro _TREED_EDDY_Z_OFFSET_AUTOSAVE_STATE',
  'gcode_macro _TREED_SYSTEM_POWER',
  'gcode_macro _TREED_CLOUD',
  'gcode_macro _TREED_UPDATES',
  'gcode_macro _TREED_CAMERA',
  'gcode_macro _TREED_SERVICE_COMMANDS',
] as const
