export const MOONRAKER_RUNTIME_OBJECTS = [
  'webhooks',
  'toolhead',
  'gcode_move',
  'print_stats',
  'virtual_sdcard',
  'extruder',
  'heater_bed',
  'fan',
  'output_pin chamber_light',
  'firmware_retraction',
  'display_status',
  'pause_resume',
  'idle_timeout',
  'save_variables',
  'gcode_macro _TREED_UI_CONTRACT',
  'gcode_macro _TREED_PROFILE',
  'gcode_macro _TREED_GEOMETRY_CFG',
  'gcode_macro _TREED_PAUSE_STATE',
  'gcode_macro _TREED_CAM_STATE',
  'gcode_macro _TREED_EDDY_Z_OFFSET_AUTOSAVE_STATE',
  'gcode_macro _TREED_SYSTEM_POWER',
  'gcode_macro _TREED_CLOUD',
  'gcode_macro _TREED_UPDATES',
  'gcode_macro _TREED_CAMERA',
  'gcode_macro _TREED_SERVICE_COMMANDS',
  'gcode_macro _TREED_UI_TUNE_STATE',
  'gcode_macro _TREED_EDDY_HOME_Z',
  'gcode_macro _TREED_EDDY_CALIBRATION_STATE',
  'gcode_macro TREED_UI_MOVE_AXIS',
  'gcode_macro TREED_UI_SET_SPEED_FACTOR',
  'gcode_macro TREED_UI_SET_FLOW_FACTOR',
  'gcode_macro TREED_UI_SET_ACCEL',
  'gcode_macro TREED_UI_SET_PRESSURE_ADVANCE',
  'gcode_macro TREED_UI_SET_RETRACTION',
  'gcode_macro TREED_UI_ADJUST_Z_OFFSET',
  'gcode_macro LIGHT_ON',
  'gcode_macro LIGHT_OFF',
  'gcode_macro LOAD_FILAMENT',
  'gcode_macro UNLOAD_FILAMENT',
  'gcode_macro TREED_Z_PARK_ZERO_EDDY',
  'gcode_macro TREED_EDDY_CALIBRATE_DRIVE_CURRENT',
  'gcode_macro TREED_EDDY_PRIMARY_HEIGHT_START',
  'gcode_macro TREED_EDDY_PRIMARY_ACCEPT_SAVE',
  'gcode_macro TREED_EDDY_TEMPERATURE_START',
  'gcode_macro TREED_EDDY_TEMPERATURE_ACCEPT_SAVE',
  'gcode_macro TREED_EDDY_CHECK_Z0',
  'gcode_macro TREED_EDDY_SCREWS_TILT_START',
  'gcode_macro TREED_EDDY_SCREWS_TILT_DONE',
  'gcode_macro TREED_EDDY_BED_MESH_CALIBRATE',
  'gcode_macro TREED_SHAPER_CALIBRATE_LIGHT',
  'gcode_macro TREED_SHAPER_CALIBRATE_FULL',
  'gcode_macro TREED_XY_MOTION_TEST',
] as const
